import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search } from "lucide-react";
import { CATEGORIES, CATEGORY_COLORS } from "../constants";
export const FilterPanel = ({ categoryFilters, onCategoryFiltersChange, timeFilter, onTimeFilterChange, searchQuery, onSearchQueryChange, }) => {
    return (_jsxs("div", { className: "w-full lg:w-64 bg-white rounded-lg shadow p-3 sm:p-4 h-fit", children: [_jsx("h3", { className: "font-semibold text-lg mb-3 sm:mb-4", children: "Filters" }), _jsxs("div", { className: "mb-3 sm:mb-4", children: [_jsx("label", { className: "block text-xs sm:text-sm font-medium mb-1 sm:mb-2", children: "Search Tasks" }), _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" }), _jsx("input", { type: "text", value: searchQuery, onChange: (e) => onSearchQueryChange(e.target.value), placeholder: "Search by name...", className: "w-full pl-9 pr-3 py-2 border rounded-md text-sm" })] })] }), _jsxs("div", { className: "mb-4", children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Categories" }), CATEGORIES.map((cat) => (_jsxs("label", { className: "flex items-center mb-2 cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: categoryFilters.includes(cat), onChange: (e) => {
                                    if (e.target.checked) {
                                        onCategoryFiltersChange([...categoryFilters, cat]);
                                    }
                                    else {
                                        onCategoryFiltersChange(categoryFilters.filter((c) => c !== cat));
                                    }
                                }, className: "mr-2" }), _jsx("span", { className: `w-3 h-3 rounded mr-2 ${CATEGORY_COLORS[cat]}` }), _jsx("span", { className: "text-sm", children: cat })] }, cat)))] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Time Range" }), [1, 2, 3].map((weeks) => (_jsxs("label", { className: "flex items-center mb-2 cursor-pointer", children: [_jsx("input", { type: "radio", name: "timeFilter", checked: timeFilter === weeks, onChange: () => onTimeFilterChange(weeks), className: "mr-2" }), _jsxs("span", { className: "text-sm", children: ["Within ", weeks, " week", weeks > 1 ? "s" : ""] })] }, weeks))), _jsxs("label", { className: "flex items-center mb-2 cursor-pointer", children: [_jsx("input", { type: "radio", name: "timeFilter", checked: timeFilter === null, onChange: () => onTimeFilterChange(null), className: "mr-2" }), _jsx("span", { className: "text-sm", children: "All tasks" })] })] })] }));
};
